description: "A new Flutter application."
name: "flutterapp"
publish_to: "none"
version: "1.0.0+1"
dependencies: 
  flutter_datetime_picker: "1.5.1"
  cupertino_icons: "^0.1.3"
  path_drawing: "^0.4.1"
  flutter: 
    sdk: "flutter"
  intl: "^0.16.1"
  cloud_firestore: ^0.11.0+2
  build_runner: ^1.12.2
dev_dependencies:
  flutter_test: 
    sdk: "flutter"
environment: 
  sdk: ">=2.7.0 <3.0.0"
flutter: 
  assets: 
    - "assets/images/"
  fonts: 
    - 
      family: "Roboto"
      fonts: 
        - 
          asset: "fonts/Roboto-500.ttf"
          style: "normal"
          weight: 500
        - 
          asset: "fonts/Roboto-700.ttf"
          style: "normal"
          weight: 700
        - 
          asset: "fonts/Roboto-100.ttf"
          style: "normal"
          weight: 100
        - 
          asset: "fonts/Roboto-regular.ttf"
          style: "normal"
          weight: 400
        - 
          asset: "fonts/Roboto-300.ttf"
          style: "normal"
          weight: 300
  uses-material-design: true
